// Code generated by Kitex v0.12.3. DO NOT EDIT.

package brokerservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	api "github.com/magicnana999/im/api/kitex_gen/api"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for cmd_service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Deliver": kitex.NewMethodInfo(
		deliverHandler,
		newDeliverArgs,
		newDeliverResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	brokerServiceServiceInfo                = NewServiceInfo()
	brokerServiceServiceInfoForClient       = NewServiceInfoForClient()
	brokerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return brokerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return brokerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return brokerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BrokerService"
	handlerType := (*api.BrokerService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func deliverHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.DeliverRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.BrokerService).Deliver(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeliverArgs:
		success, err := handler.(api.BrokerService).Deliver(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeliverResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeliverArgs() interface{} {
	return &DeliverArgs{}
}

func newDeliverResult() interface{} {
	return &DeliverResult{}
}

type DeliverArgs struct {
	Req *api.DeliverRequest
}

func (p *DeliverArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.DeliverRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeliverArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeliverArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeliverArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeliverArgs) Unmarshal(in []byte) error {
	msg := new(api.DeliverRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeliverArgs_Req_DEFAULT *api.DeliverRequest

func (p *DeliverArgs) GetReq() *api.DeliverRequest {
	if !p.IsSetReq() {
		return DeliverArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeliverArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeliverArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeliverResult struct {
	Success *api.DeliverReply
}

var DeliverResult_Success_DEFAULT *api.DeliverReply

func (p *DeliverResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.DeliverReply)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeliverResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeliverResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeliverResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeliverResult) Unmarshal(in []byte) error {
	msg := new(api.DeliverReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeliverResult) GetSuccess() *api.DeliverReply {
	if !p.IsSetSuccess() {
		return DeliverResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeliverResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.DeliverReply)
}

func (p *DeliverResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeliverResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Deliver(ctx context.Context, Req *api.DeliverRequest) (r *api.DeliverReply, err error) {
	var _args DeliverArgs
	_args.Req = Req
	var _result DeliverResult
	if err = p.c.Call(ctx, "Deliver", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
