version: '3.8'

services:
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.0
    restart: unless-stopped
    ports:
      - 2379:2379
      - 2380:2380
    command: >
      /usr/local/bin/etcd
        --name node1
        --data-dir=/etcd-data
        --listen-client-urls    http://0.0.0.0:2379
        --listen-peer-urls      http://0.0.0.0:2380
        --advertise-client-urls http://127.0.0.1:2379
        --initial-advertise-peer-urls http://127.0.0.1:2380
        --initial-cluster node1=http://127.0.0.1:2380
        --auto-compaction-mode=periodic 
        --auto-compaction-retention=30m
    volumes:
      - ~/volumes/im/etcd/data:/etcd-data
      - ~/volumes/im/etcd/logs:/var/log/etcd

  mysql:
    image: mysql:8.0.29
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: im
    volumes:
      - ~/volumes/im/mysql/data:/var/lib/mysql
      - ~/volumes/im/mysql/logs:/var/log/mysql
      - ~/volumes/im/mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - im-network

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ~/volumes/im/redis/data:/data
      - ~/volumes/im/redis/logs:/var/log/redis
      - ~/volumes/im/redis/conf:/usr/local/etc/redis
    ports:
      - "6379:6379"
    networks:
      - im-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ~/volumes/im/kafka/data:/opt/kafka/data
      - ~/volumes/im/kafka/logs:/opt/kafka/logs
      - ~/volumes/im/kafka/conf:/opt/kafka/config
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "./opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - im-network

networks:
  im-network:
    driver: bridge