version: '3.8'




services:


  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.0
    restart: unless-stopped
    ports:
      - 2379:2379
      - 2380:2380
    command: >
      /usr/local/bin/etcd
        --name node1
        --data-dir=/etcd-data
        --listen-client-urls    http://0.0.0.0:2379
        --listen-peer-urls      http://0.0.0.0:2380
        --advertise-client-urls http://127.0.0.1:2379
        --initial-advertise-peer-urls http://127.0.0.1:2380
        --initial-cluster node1=http://127.0.0.1:2380
        --auto-compaction-mode=periodic 
        --auto-compaction-retention=30m
  

  mysql:
    image: mysql:8.0.29 # 使用 MySQL 8.x 的稳定版本
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: im
    volumes:
      - /Users/jinsong/volumes/im/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - im-network

  redis:
    image: redis:latest # 使用 Redis 7.x 的稳定版本
    container_name: cache
    volumes:
      - /Users/jinsong/volumes/im/cache:/data
    ports:
      - "6379:6379"
    networks:
      - im-network

  kafka:
    image: apache/kafka # 使用 Kafka 3.9.0 raft 版本
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SSL_PORT: 9094
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_LISTENER_PORT: 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    volumes:
      - /Users/jinsong/volumes/im/kafka:/var/lib/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - im-network

  elasticsearch:
    image: elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - /Users/jinsong/volumes/im/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - im-network

networks:
  im-network:
    driver: bridge
