// Code generated by Kitex v0.12.3. DO NOT EDIT.

package routerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "main/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for api framework.
type Client interface {
	Route(ctx context.Context, req *api.RouteRequest, callOptions ...callopt.Option) (r *api.RouteResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRouterServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRouterServiceClient struct {
	*kClient
}

func (p *kRouterServiceClient) Route(ctx context.Context, req *api.RouteRequest, callOptions ...callopt.Option) (r *api.RouteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Route(ctx, req)
}
