// Code generated by Kitex v0.12.3. DO NOT EDIT.

package routerservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "main/kitex_gen/api"
)

var errInvalidMessageType = errors.New("invalid message type for cmd_service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"route": kitex.NewMethodInfo(
		routeHandler,
		newRouterServiceRouteArgs,
		newRouterServiceRouteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	routerServiceServiceInfo                = NewServiceInfo()
	routerServiceServiceInfoForClient       = NewServiceInfoForClient()
	routerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return routerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return routerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return routerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RouterService"
	handlerType := (*api.RouterService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func routeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.RouterServiceRouteArgs)
	realResult := result.(*api.RouterServiceRouteResult)
	success, err := handler.(api.RouterService).Route(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouterServiceRouteArgs() interface{} {
	return api.NewRouterServiceRouteArgs()
}

func newRouterServiceRouteResult() interface{} {
	return api.NewRouterServiceRouteResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Route(ctx context.Context, req *api.RouteRequest) (r *api.RouteResponse, err error) {
	var _args api.RouterServiceRouteArgs
	_args.Req = req
	var _result api.RouterServiceRouteResult
	if err = p.c.Call(ctx, "route", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
