// Code generated by Kitex v0.12.3. DO NOT EDIT.

package routerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "github.com/magicnana999/im/api/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Route(ctx context.Context, Req *api.Message, callOptions ...callopt.Option) (r *api.Message, err error)
}

// NewClient creates a client for the cmd_service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRouterServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the cmd_service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRouterServiceClient struct {
	*kClient
}

func (p *kRouterServiceClient) Route(ctx context.Context, Req *api.Message, callOptions ...callopt.Option) (r *api.Message, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Route(ctx, Req)
}
