// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package api

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *DeliverRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeliverRequest[number], err)
}

func (x *DeliverRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.MessageId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *DeliverRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var v string
	v, offset, err = fastpb.ReadString(buf, _type)
	if err != nil {
		return offset, err
	}
	x.UserLabels = append(x.UserLabels, v)
	return offset, err
}

func (x *DeliverRequest) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var v Message
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Message = &v
	return offset, nil
}

func (x *DeliverReply) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeliverReply[number], err)
}

func (x *DeliverReply) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.MessageId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *DeliverReply) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Code, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *DeliverReply) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Message, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *DeliverRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *DeliverRequest) fastWriteField1(buf []byte) (offset int) {
	if x.MessageId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetMessageId())
	return offset
}

func (x *DeliverRequest) fastWriteField2(buf []byte) (offset int) {
	if len(x.UserLabels) == 0 {
		return offset
	}
	for i := range x.GetUserLabels() {
		offset += fastpb.WriteString(buf[offset:], 2, x.GetUserLabels()[i])
	}
	return offset
}

func (x *DeliverRequest) fastWriteField3(buf []byte) (offset int) {
	if x.Message == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 3, x.GetMessage())
	return offset
}

func (x *DeliverReply) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *DeliverReply) fastWriteField1(buf []byte) (offset int) {
	if x.MessageId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetMessageId())
	return offset
}

func (x *DeliverReply) fastWriteField2(buf []byte) (offset int) {
	if x.Code == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 2, x.GetCode())
	return offset
}

func (x *DeliverReply) fastWriteField3(buf []byte) (offset int) {
	if x.Message == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetMessage())
	return offset
}

func (x *DeliverRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *DeliverRequest) sizeField1() (n int) {
	if x.MessageId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetMessageId())
	return n
}

func (x *DeliverRequest) sizeField2() (n int) {
	if len(x.UserLabels) == 0 {
		return n
	}
	for i := range x.GetUserLabels() {
		n += fastpb.SizeString(2, x.GetUserLabels()[i])
	}
	return n
}

func (x *DeliverRequest) sizeField3() (n int) {
	if x.Message == nil {
		return n
	}
	n += fastpb.SizeMessage(3, x.GetMessage())
	return n
}

func (x *DeliverReply) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *DeliverReply) sizeField1() (n int) {
	if x.MessageId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetMessageId())
	return n
}

func (x *DeliverReply) sizeField2() (n int) {
	if x.Code == 0 {
		return n
	}
	n += fastpb.SizeInt32(2, x.GetCode())
	return n
}

func (x *DeliverReply) sizeField3() (n int) {
	if x.Message == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetMessage())
	return n
}

var fieldIDToName_DeliverRequest = map[int32]string{
	1: "MessageId",
	2: "UserLabels",
	3: "Message",
}

var fieldIDToName_DeliverReply = map[int32]string{
	1: "MessageId",
	2: "Code",
	3: "Message",
}
