// Code generated by Kitex v0.12.3. DO NOT EDIT.

package routerservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	api "github.com/magicnana999/im/api/kitex_gen/api"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Route": kitex.NewMethodInfo(
		routeHandler,
		newRouteArgs,
		newRouteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	routerServiceServiceInfo                = NewServiceInfo()
	routerServiceServiceInfoForClient       = NewServiceInfoForClient()
	routerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return routerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return routerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return routerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RouterService"
	handlerType := (*api.RouterService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func routeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.Message)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.RouterService).Route(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RouteArgs:
		success, err := handler.(api.RouterService).Route(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RouteResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRouteArgs() interface{} {
	return &RouteArgs{}
}

func newRouteResult() interface{} {
	return &RouteResult{}
}

type RouteArgs struct {
	Req *api.Message
}

func (p *RouteArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.Message)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *RouteArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *RouteArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *RouteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RouteArgs) Unmarshal(in []byte) error {
	msg := new(api.Message)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RouteArgs_Req_DEFAULT *api.Message

func (p *RouteArgs) GetReq() *api.Message {
	if !p.IsSetReq() {
		return RouteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RouteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RouteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RouteResult struct {
	Success *api.RouteReply
}

var RouteResult_Success_DEFAULT *api.RouteReply

func (p *RouteResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.RouteReply)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *RouteResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *RouteResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *RouteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RouteResult) Unmarshal(in []byte) error {
	msg := new(api.RouteReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RouteResult) GetSuccess() *api.RouteReply {
	if !p.IsSetSuccess() {
		return RouteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RouteResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.RouteReply)
}

func (p *RouteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RouteResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Route(ctx context.Context, Req *api.Message) (r *api.RouteReply, err error) {
	var _args RouteArgs
	_args.Req = Req
	var _result RouteResult
	if err = p.c.Call(ctx, "Route", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
