// Code generated by Kitex v0.12.3. DO NOT EDIT.

package brokerservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "main/kitex_gen/api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"deliver": kitex.NewMethodInfo(
		deliverHandler,
		newBrokerServiceDeliverArgs,
		newBrokerServiceDeliverResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	brokerServiceServiceInfo                = NewServiceInfo()
	brokerServiceServiceInfoForClient       = NewServiceInfoForClient()
	brokerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return brokerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return brokerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return brokerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BrokerService"
	handlerType := (*api.BrokerService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func deliverHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.BrokerServiceDeliverArgs)
	realResult := result.(*api.BrokerServiceDeliverResult)
	success, err := handler.(api.BrokerService).Deliver(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBrokerServiceDeliverArgs() interface{} {
	return api.NewBrokerServiceDeliverArgs()
}

func newBrokerServiceDeliverResult() interface{} {
	return api.NewBrokerServiceDeliverResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Deliver(ctx context.Context, req *api.DeliverRequest) (r *api.DeliverResponse, err error) {
	var _args api.BrokerServiceDeliverArgs
	_args.Req = req
	var _result api.BrokerServiceDeliverResult
	if err = p.c.Call(ctx, "deliver", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
